# This is a config for E2B sandbox template.
# You can use template ID (smiijka1ts0v6gxmmk8n) or template name (code-x-nextjs-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("code-x-nextjs-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("code-x-nextjs-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('code-x-nextjs-2')

team_id = "06fa4b16-5a68-4ab3-84a9-c1b8c01a9f9d"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "code-x-nextjs-2"
template_id = "smiijka1ts0v6gxmmk8n"
